[project]
name = "dspy-wikipedia-qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "alembic==1.16.5",
    "annotated-types==0.7.0",
    "anyio==4.10.0",
    "asyncer==0.0.8",
    "attrs==25.3.0",
    "backoff==2.2.1",
    "cachetools==6.2.0",
    "certifi==2025.8.3",
    "charset-normalizer==3.4.3",
    "click==8.2.1",
    "cloudpickle==3.1.1",
    "coloredlogs==15.0.1",
    "colorlog==6.9.0",
    "datasets==4.0.0",
    "dill==0.3.8",
    "diskcache==5.6.3",
    "distro==1.9.0",
    "dspy==3.0.2",
    "dspy-ai==3.0.2",
    "filelock==3.19.1",
    "flatbuffers==25.2.10",
    "frozenlist==1.7.0",
    "fsspec==2025.3.0",
    "gepa==0.0.4",
    "greenlet==3.2.4",
    "grpcio==1.74.0",
    "h11==0.16.0",
    "hf-xet==1.1.9",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "huggingface-hub==0.34.4",
    "humanfriendly==10.0",
    "idna==3.10",
    "importlib-metadata==8.7.0",
    "jinja2==3.1.6",
    "jiter==0.10.0",
    "joblib==1.5.2",
    "json-repair==0.50.0",
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.4.1",
    "litellm==1.76.0",
    "magicattr==0.1.6",
    "mako==1.3.10",
    "markdown-it-py==4.0.0",
    "markupsafe==3.0.2",
    "mdurl==0.1.2",
    "milvus-lite==2.5.1",
    "mpmath==1.3.0",
    "multidict==6.6.4",
    "multiprocess==0.70.16",
    "numpy==2.3.2",
    "onnxruntime==1.22.1",
    "openai==1.102.0",
    "optuna==4.5.0",
    "packaging==25.0",
    "pandas==2.3.2",
    "propcache==0.3.2",
    "protobuf==6.32.0",
    "pyarrow==21.0.0",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pygments==2.19.2",
    "pymilvus==2.6.0",
    "pymilvus-model==0.3.2",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.1",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "referencing==0.36.2",
    "regex==2025.7.34",
    "requests==2.32.5",
    "rich==14.1.0",
    "rpds-py==0.27.1",
    "safetensors==0.6.2",
    "scipy==1.16.1",
    "setuptools==80.9.0",
    "shellingham==1.5.4",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.43",
    "sympy==1.14.0",
    "tenacity==9.1.2",
    "tensorflow>=2.20.0",
    "tiktoken==0.11.0",
    "tokenizers==0.21.4",
    "tqdm==4.67.1",
    "transformers==4.55.4",
    "typer==0.16.1",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.1",
    "tzdata==2025.2",
    "ujson==5.11.0",
    "urllib3==2.5.0",
    "wikipedia-api==0.8.1",
    "xxhash==3.5.0",
    "yarl==1.20.1",
    "zipp==3.23.0",
]
